# Week 8 Overview

This week will be a mix of data joining/merging problems and linear algebra. 
The first 5 problems are data cleaning and the final 4 problems are linear algebra.

There are multiple ways to combine data. These methods are common cross multiple languages like pandas, SQL, and R. At times the naming is different but the general concepts apply. 

### **Joining or Merging**
This is a process of combining two datasets by adding the columns of one dataset to the other by some logical relationship between the columns. 

In SQL we call this joining but pandas has two functions:

**merge** - The default behavor for merge is to combine on columns matching.

**join** - The default behavor for join is to combine on the column index matching. 

Often times I will colloquially use the word "join" for either merging or joining in pandas. 

Left Dataset
| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |

Right Dataset
| key    | different_value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

Data Joined on key

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | cat |
| A2 | $80     | dog |
| A3    | $420    | apple |

Typically we refer to the starting dataset as the left dataset and the one being added as the right. 

The logic is typically that there is the same value in a specific column in both datasets. SQL allows for slightly more advanced logic which we will learn next quarter. Today we will focus on just columns matching. 

There are different types of joins that you will explore in this notebook (inner, outer, left, right, cross). The typical visual that is used to illustration these concepts in Ven Diagrams. If you are getting stuck trying to pick the right join type search for "types of joins" and look at the pictures that come up.


## **Concat or Union**

This is a process of combining two dataset by adding the rows of one dataset to the end of another. There is no logic required for this. This is called conact in pandas and union in SQL. 

In most version of SQL you are required to have the same columns in both datasets. In pandas you don't have to. If I concatenate the two dataset above in pandas I would get:

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | null |
| A2 | $80     | null |
| A3    | $420    | null |
| A1  | null    | cat |
| A2 | null     | dog |
| A3    | null    | apple |

However if my right dataset looked like this:

| key    | value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

then I could union them in SQL or concat in pandas to get:

| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

In [1]:
import pandas as pd
import numpy as np

In [13]:
df_1 = pd.DataFrame({"ints": range(100)})
df_2 = pd.DataFrame({"ints": range(-10, 10)}, index=range(-10, 10))


df_1['threes'] = np.floor(df_1['ints']/3) * 3

df_2['evens'] = df_2['ints']*2
df_2['threes'] = np.floor(df_2['ints']/3) * 3

df_1
df_2

     ints  evens  threes
-10   -10    -20   -12.0
-9     -9    -18    -9.0
-8     -8    -16    -9.0
-7     -7    -14    -9.0
-6     -6    -12    -6.0
-5     -5    -10    -6.0
-4     -4     -8    -6.0
-3     -3     -6    -3.0
-2     -2     -4    -3.0
-1     -1     -2    -3.0
0       0      0     0.0
1       1      2     0.0
2       2      4     0.0
3       3      6     3.0
4       4      8     3.0
5       5     10     3.0
6       6     12     6.0
7       7     14     6.0
8       8     16     6.0
9       9     18     9.0

### Problem 1:

Your first task will be to create a dataset by `merging` `df_1` and `df_2` on the `ints` column where the match on both sides. The results will be a dataframe with 10 rows and 5 columns.

You will then create the same dataframe by using the `join` function and joining the two datasets where the indexes are equal. There will be a little more work of handle column duplication so look up the error and figure out arguments to set. How many columns do you get in this case?

In [3]:
df = pd.merge(df_1, df_2)
df

   ints  threes  evens
0     0     0.0      0
1     1     0.0      2
2     2     0.0      4
3     3     3.0      6
4     4     3.0      8
5     5     3.0     10
6     6     6.0     12
7     7     6.0     14
8     8     6.0     16
9     9     9.0     18

In [4]:
df_3 = pd.merge(df_1, df_2, on='ints', how='left')
df_3

    ints  threes_x  evens  threes_y
0      0       0.0    0.0       0.0
1      1       0.0    2.0       0.0
2      2       0.0    4.0       0.0
3      3       3.0    6.0       3.0
4      4       3.0    8.0       3.0
..   ...       ...    ...       ...
95    95      93.0    NaN       NaN
96    96      96.0    NaN       NaN
97    97      96.0    NaN       NaN
98    98      96.0    NaN       NaN
99    99      99.0    NaN       NaN

[100 rows x 4 columns]

## Problem 2:

Next you will perform the same merge as above three times with the following modifications:

* You want to keep all rows in `df_1` even if there is no match found in `df_2`
* You want to keep all rows in `df_2` even if there is no match found in `df_1`
* You want to keep all rows in `df_1` and `df_2` even if there is no match found in the other dataframe


How many rows do you end up with in each case? 

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [5]:
left_merge = pd.merge(df_1, df_2, on="ints", how="left")
print(len(left_merge))


print(left_merge.shape)
left_merge

100
(100, 4)

    ints  threes_x  evens  threes_y
0      0       0.0    0.0       0.0
1      1       0.0    2.0       0.0
2      2       0.0    4.0       0.0
3      3       3.0    6.0       3.0
4      4       3.0    8.0       3.0
..   ...       ...    ...       ...
95    95      93.0    NaN       NaN
96    96      96.0    NaN       NaN
97    97      96.0    NaN       NaN
98    98      96.0    NaN       NaN
99    99      99.0    NaN       NaN

[100 rows x 4 columns]

In [6]:
right_merge = pd.merge(df_1, df_2, on="ints", how="right")
print(len(right_merge))

print(right_merge.shape)
right_merge

20
(20, 4)

    ints  threes_x  evens  threes_y
0    -10       NaN    -20     -12.0
1     -9       NaN    -18      -9.0
2     -8       NaN    -16      -9.0
3     -7       NaN    -14      -9.0
4     -6       NaN    -12      -6.0
5     -5       NaN    -10      -6.0
6     -4       NaN     -8      -6.0
7     -3       NaN     -6      -3.0
8     -2       NaN     -4      -3.0
9     -1       NaN     -2      -3.0
10     0       0.0      0       0.0
11     1       0.0      2       0.0
12     2       0.0      4       0.0
13     3       3.0      6       3.0
14     4       3.0      8       3.0
15     5       3.0     10       3.0
16     6       6.0     12       6.0
17     7       6.0     14       6.0
18     8       6.0     16       6.0
19     9       9.0     18       9.0

In [7]:
outer_merge = pd.merge(df_1, df_2, on="ints", how="outer")
print(len(outer_merge))

print(outer_merge.shape)
outer_merge

110
(110, 4)

     ints  threes_x  evens  threes_y
0     -10       NaN  -20.0     -12.0
1      -9       NaN  -18.0      -9.0
2      -8       NaN  -16.0      -9.0
3      -7       NaN  -14.0      -9.0
4      -6       NaN  -12.0      -6.0
..    ...       ...    ...       ...
105    95      93.0    NaN       NaN
106    96      96.0    NaN       NaN
107    97      96.0    NaN       NaN
108    98      96.0    NaN       NaN
109    99      99.0    NaN       NaN

[110 rows x 4 columns]

### Problem 3

Now we are going to merge on columns that are not the same. Merge on the following:

* Merge `df_1` and `df_2` where `df_1.ints = df_2.evens`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, keep all rows from `df_1` even if there is no match found in `df_2`
* Merge `df_1` and `df_2` where `df_1.threes = df_2.threes`, only keep rows where there is a value for either dataframe


How many rows do you end up with in each case? Are there any duplications? (try: value_count)

Think through a scenario where you might want to do this and add it as a comment above each merge.

In [8]:
m1 = pd.merge(df_1, df_2, left_on="ints", right_on="evens", how="inner")
len(m1)

m1

   ints_x  threes_x  ints_y  evens  threes_y
0       0       0.0       0      0       0.0
1       2       0.0       1      2       0.0
2       4       3.0       2      4       0.0
3       6       6.0       3      6       3.0
4       8       6.0       4      8       3.0
5      10       9.0       5     10       3.0
6      12      12.0       6     12       6.0
7      14      12.0       7     14       6.0
8      16      15.0       8     16       6.0
9      18      18.0       9     18       9.0

In [9]:
m2 = pd.merge(df_1, df_2, left_on="ints", right_on="threes", how="inner")
len(m2)

m2

   ints_x  threes_x  ints_y  evens  threes_y
0       0       0.0       0      0       0.0
1       0       0.0       1      2       0.0
2       0       0.0       2      4       0.0
3       3       3.0       3      6       3.0
4       3       3.0       4      8       3.0
5       3       3.0       5     10       3.0
6       6       6.0       6     12       6.0
7       6       6.0       7     14       6.0
8       6       6.0       8     16       6.0
9       9       9.0       9     18       9.0

In [10]:
m3 = pd.merge(df_1, df_2, left_on="ints", right_on="threes", how="left")
len(m3)

m3

     ints_x  threes_x  ints_y  evens  threes_y
0         0       0.0     0.0    0.0       0.0
1         0       0.0     1.0    2.0       0.0
2         0       0.0     2.0    4.0       0.0
3         1       0.0     NaN    NaN       NaN
4         2       0.0     NaN    NaN       NaN
..      ...       ...     ...    ...       ...
101      95      93.0     NaN    NaN       NaN
102      96      96.0     NaN    NaN       NaN
103      97      96.0     NaN    NaN       NaN
104      98      96.0     NaN    NaN       NaN
105      99      99.0     NaN    NaN       NaN

[106 rows x 5 columns]

In [11]:
m4 = pd.merge(df_1, df_2, on="threes", how="inner")
len(m4)

m4

    ints_x  threes  ints_y  evens
0        0     0.0       0      0
1        0     0.0       1      2
2        0     0.0       2      4
3        1     0.0       0      0
4        1     0.0       1      2
5        1     0.0       2      4
6        2     0.0       0      0
7        2     0.0       1      2
8        2     0.0       2      4
9        3     3.0       3      6
10       3     3.0       4      8
11       3     3.0       5     10
12       4     3.0       3      6
13       4     3.0       4      8
14       4     3.0       5     10
15       5     3.0       3      6
16       5     3.0       4      8
17       5     3.0       5     10
18       6     6.0       6     12
19       6     6.0       7     14
20       6     6.0       8     16
21       7     6.0       6     12
22       7     6.0       7     14
23       7     6.0       8     16
24       8     6.0       6     12
25       8     6.0       7     14
26       8     6.0       8     16
27       9     9.0       9     18
28      10     9.0       9     18
29      11     9.0       9     18

### Problem 4

Add a new the column to `df_2` called `threes_string` that is the `threes` column converted to a string. Attempt to merge `df_1` and `df_2` where `df_1.threes = df_2.threes_string` with an inner join. What happens? Why?

In [ ]:
# this returns error
df_2["threes_string"] = df_2["threes"].astype(str)
# convert df_1 to string
df_1['threes_string'] = df_1['threes'].astype(str)

df_1.merge(
    df_2,
    left_on="threes_string",
    right_on="threes_string",
    how="inner"
)

    ints_x  threes_x threes_string  ints_y  evens  threes_y
0        0       0.0           0.0       0      0       0.0
1        0       0.0           0.0       1      2       0.0
2        0       0.0           0.0       2      4       0.0
3        1       0.0           0.0       0      0       0.0
4        1       0.0           0.0       1      2       0.0
5        1       0.0           0.0       2      4       0.0
6        2       0.0           0.0       0      0       0.0
7        2       0.0           0.0       1      2       0.0
8        2       0.0           0.0       2      4       0.0
9        3       3.0           3.0       3      6       3.0
10       3       3.0           3.0       4      8       3.0
11       3       3.0           3.0       5     10       3.0
12       4       3.0           3.0       3      6       3.0
13       4       3.0           3.0       4      8       3.0
14       4       3.0           3.0       5     10       3.0
15       5       3.0           3.0       3      6       3.0
16       5       3.0           3.0       4      8       3.0
17       5       3.0           3.0       5     10       3.0
18       6       6.0           6.0       6     12       6.0
19       6       6.0           6.0       7     14       6.0
20       6       6.0           6.0       8     16       6.0
21       7       6.0           6.0       6     12       6.0
22       7       6.0           6.0       7     14       6.0
23       7       6.0           6.0       8     16       6.0
24       8       6.0           6.0       6     12       6.0
25       8       6.0           6.0       7     14       6.0
26       8       6.0           6.0       8     16       6.0
27       9       9.0           9.0       9     18       9.0
28      10       9.0           9.0       9     18       9.0
29      11       9.0           9.0       9     18       9.0

### Problem 5

Now you will play around with `pd.concat` by doing the following:

* Concatenate `df_1` and `df_2` keeping all rows, columns and indexes
* Concatenate `df_1` and `df_2` keeping all rows and columns but ignore the indexes from the orginal dataframes and instead have the index on this dataframe be zero to the number of rows.
* Concatenate `df_1` and `df_2` keeping all rows and indexes the same but only keeping columns that exist in both dataframes

In [31]:
c1 = pd.concat([df_1, df_2])
print(c1.shape)

c2 = pd.concat([df_1, df_2], ignore_index=True)
print(c2.shape)

c3 = pd.concat([df_1, df_2], join="inner")
print(c3.shape)

(120, 4)
(120, 4)
(120, 3)

## Linear Algebra: Rank and Column Space

### Problem 6
You will now learn how to create random matrices with arbitrary rank (subject to the constraints about matrix sizes, etc.). To create an $m \times n$ matrix with rank $r$, multiply a random $m \times r$ matrix with a random $r \times n$ matrix. Implement this in Python and confirm that the rank is indeed $r$. 

What happens if you set $r > min{M,N}$, and why does that happen?

shape: (8, 5)
desired rank r: 3
computed rank: 3

when r2 > min(m,n)
shape: (8, 5)
r2: 10 min(m,n): 5
computed rank: 5

### Problem 7
Interestingly, the matrices $A$, $A^T$, $A^T A$, and $AA^T$ all have the same rank. Write code to demonstrate this, using random matrices of various sizes, shapes (square, tall, wide), and ranks. Create a total of 6 random, two of each size that have different sizes and ranks.

### Problem 8

Demonstrate the addition rule of matrix rank $(r(A + B) ≤ r(A) + r(B))$ by creating three pairs of rank-1 matrices that have a sum with 
1. rank-0
2. rank-1
3. rank-2

Then repeat this exercise using matrix multiplication instead of addition.

### Problem 9

The goal of this exercise is to answer the question is $v \in C(A)$?

Create a rank-3 matrix $A \in \mathbb{R}^{4 \times 3}$ and vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. 

Follow the algorithm described in the [In the Column Space?](https://learning.oreilly.com/library/view/practical-linear-algebra/9781098120603/ch06.html#id335) section of Practical Linear Algebra to determine whether the vector is in the column space of the matrix. 

Rerun the code multiple times to see whether you find a consistent pattern. 

Next, use a $A \in \mathbb{R}^{4 \times 4}$ rank-4 matrix and a vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. What happens in this case? Why?